### PR TITLE
Add cargo fmt to travis build config

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by Atul9** [comment]
@nical Is travis build disabled? Can you please enable it?

**Comment by nical** [comment]
Sorry for the delay, I moved the CI to github actions in #18. What would the cargo format integration do? would it add review comments or make the CI fail when something isn't formatted in a standard way?

**Comment by Atul9** [comment]
`cargo fmt` will make the CI fail when something isn't formatted in a standard way.

**Comment by nical** [comment]
Then I would rather not. It's good to run the formatter every now and then to keep things mostly consistent but this type of thing shouldn't get in the way if it doesn't need to (and I don't think it needs to for this kind of project).

**Comment by Atul9** [comment]
ok

**Pull request closed without merging**
